import React from 'react'
import Head from 'next/head'
import Header from '../components/Header.js'
import Footer from '../components/Footer.js'

import style from '../styles/Contact.module.css'

const Contact = () => {

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header id="home">
                <Header />
            </header>
            <main>
                <div className={style.contact_flex_center}>
                    <div className={style.contact_width}>

                        <Footer />
                    </div>
                </div>
            </main>

        </div>
    )
}

export default Contact