import React, { useState } from 'react'
import Head from 'next/head'
import Header from '../components/Header.js'
import Footer from '../components/Footer.js'
import PlanOptions from '../components/PlanOptions.js'
import Image from 'next/image'
import Link from 'next/link'
import * as MdIcons from 'react-icons/md'
import * as IoIcons from 'react-icons/io5'
import HeroImage from '../assets/images/hero-image.png'
import FeaturesImage from '../assets/images/features.png'
import BinanceLogo from '../assets/logos/binance.png'
import KrakenLogo from '../assets/logos/kraken.png'
import HuobiLogo from '../assets/logos/huobi.png'
import OkexLogo from '../assets/logos/okex.png'
import FtxLogo from '../assets/logos/ftx.png'
import BybitLogo from '../assets/logos/bybit.png'
import style from '../styles/Home.module.css'

const Home = () => {
  const [planType, setPlantype] = useState('annual')

  return (
    <div>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header id="home">
        <Header />
      </header>

      <main>
        <div className={style.home_flex_center}>
          <div className={style.home_width}>
            <div className={style.home_hero_section}>
              <div>
                <h1 className={style.home_hero_section_title}>Automate your<br />trading strategies</h1>
                <h2 className={style.home_hero_section_subtitle} >Create your custom crypto trading bot without coding skills and never miss an opportunity or get caught in a dip.</h2>
                <div style={{ width: '100%', display: 'flex', justifyContent: 'center', marginTop: 40 }}>
                  <div className={style.homepage_getstarted_button}>
                    <Link href="https://app.tradingrid.com/signup"><a style={{ marginLeft: 14, fontSize: 16, fontWeight: 600 }}>Start Now</a></Link>
                    <MdIcons.MdChevronRight size={24} style={{ marginTop: 1 }} />
                  </div>
                </div>
              </div>
            </div>
            <div className={style.home_flex_center}>
              <div style={{ width: 900 }}>
                <Image src={HeroImage} alt="home_image" className={style.home_image_cotainer} />
              </div>
            </div>
            <div className={style.home_section_container_exchanges}>
              <div style={{ marginTop: 40, marginBottom: 10 }}>
                <div className={style.home_section_box_exchanges}>
                  <div style={{ width: 230, height: 50, marginRight: 70, marginBottom: 20 }}>
                    <Image src={BinanceLogo} alt="binance" className={style.home_exchange_logo} />
                  </div>
                  <div style={{ width: 110, height: 50, marginRight: 70, marginBottom: 20 }}>
                    <Image src={BybitLogo} alt="bybit" className={style.home_exchange_logo} />
                  </div>
                  <div style={{ width: 190, height: 50, marginRight: 70, marginTop: 12, marginBottom: 5 }}>
                    <Image src={KrakenLogo} alt="kraken" className={style.home_exchange_logo} />
                  </div>
                  <div style={{ width: 240, height: 50, marginRight: 70, marginTop: 11, marginBottom: 15 }}>
                    <Image src={HuobiLogo} alt="huobi" className={style.home_exchange_logo} />
                  </div>
                  <div style={{ width: 140, height: 50, marginRight: 70, marginBottom: 20, marginTop: 5 }}>
                    <Image src={FtxLogo} alt="ftx" className={style.home_exchange_logo} />
                  </div>
                  <div style={{ width: 160, height: 50, marginRight: 70, marginBottom: 40, marginTop: 3 }}>
                    <Image src={OkexLogo} alt="okex" className={style.home_exchange_logo} />
                  </div>
                </div>
              </div>
            </div>
            <div className={style.home_flex_center} id="about">
              <div style={{ maxWidth: 650, marginBottom: 10 }}>
                <h2 className={style.home_features_section_title}>Level up your trading strategies</h2>
                <p className={style.home_features_section_description}>We’ve created a modern bot builder that execute transactions according to the parameters you set, and we have connected crypto exchanges and financial protection algorithms to it.</p>
              </div>
            </div>
            <div className={style.home_section_container}>
              <ul className={style.home_section_about}>
                <li className={style.home_section_about_list}>
                  <div className={style.home_section_about_icon}>
                    <IoIcons.IoCloudDone size={32} color="rgb(130, 87, 230)" />
                  </div>
                  <h3 className={style.home_section_about_title}>Cloud-based</h3>
                  <p className={style.home_section_about_description}>Your bots run reliably 24/7 and never miss a trade, we eliminate the need to setup your own server.</p>
                </li>
                <li className={style.home_section_about_list}>
                  <div className={style.home_section_about_icon}>
                    <IoIcons.IoStatsChart size={30} color="rgb(130, 87, 230)" />
                  </div>
                  <h3 className={style.home_section_about_title}>Multiple indicators</h3>
                  <p className={style.home_section_about_description}>We offer more than 50 advance indicators including moving averages and candle patterns detection.</p>
                </li>
                <li className={style.home_section_about_list}>
                  <div className={style.home_section_about_icon}>
                    <IoIcons.IoWallet size={32} color="rgb(130, 87, 230)" />
                  </div>
                  <h3 className={style.home_section_about_title}>Secure</h3>
                  <p className={style.home_section_about_description}>Keep your funds safe on your own exchange. The communication is made by official exchange APIs.</p>
                </li>
                <li className={style.home_section_about_list}>
                  <div className={style.home_section_about_icon}>
                    <IoIcons.IoServer size={32} color="rgb(130, 87, 230)" />
                  </div>
                  <h3 className={style.home_section_about_title}>High frequence</h3>
                  <p className={style.home_section_about_description}>Algorithms and indicators are calculated in real-time in our powerful servers based on live market data.</p>
                </li>
                <li className={style.home_section_about_list}>
                  <div className={style.home_section_about_icon}>
                    <IoIcons.IoPlay size={32} color="rgb(130, 87, 230)" />
                  </div>
                  <h3 className={style.home_section_about_title}>Easy to start</h3>
                  <p className={style.home_section_about_description}>No code skills are required, you can build your strategy easily by selecting your favorite indicators.</p>
                </li>
                <li className={style.home_section_about_list}>
                  <div className={style.home_section_about_icon}>
                    <IoIcons.IoBagCheck size={32} color="rgb(130, 87, 230)" />
                  </div>
                  <h3 className={style.home_section_about_title}>Encrypted</h3>
                  <p className={style.home_section_about_description}>We store API keys in encrypted form AES 256 and all trading operations are end-to-end encrypted.</p>
                </li>
              </ul>
            </div>
            <div className={style.home_flex_center}>
              <div className={style.home_middle_section}>
                <div className={style.home_flex_center}>
                  <h2 className={style.home_middle_section_title}>Professional tools for automating trading on cryptocurrency exchanges</h2>
                </div>
                <div className={style.home_flex_center}>
                  <div style={{ maxWidth: 700 }}>
                    <Image src={HeroImage} alt="home_image" className={style.home_image_cotainer} />
                  </div>
                </div>
              </div>
            </div>
            <div className={style.home_flex_center} id="features">
              <div style={{ maxWidth: 600, marginBottom: 50 }}>
                <h2 className={style.home_features_section_title}>Built for your workflow</h2>
                <p className={style.home_features_section_description}>Tradingrid provides all tools for the creation of your custom trade automation, allowing you to remove the emotions from your operations and get stick with the strategy as a professional.</p>
              </div>
            </div>
            <div className={style.home_features_section_container_01}>
              <div>
                <h3 className={style.home_features_section_subtitle} style={{ textAlign: 'center' }}>Setup your exchange</h3>
                <p className={style.home_features_section_text} style={{ textAlign: 'center' }}>Start selectting your favorite exchange and connect with your API keys. We also provide an demo exchange by default for tests purposes before your strategy go live. Spot trading is avaliable with Binance, Kraken, FTX and OKEx, while Margin/Leverage is supported with ByBit.</p>
              </div>
              <div style={{ marginBottom: 20 }}>
                <div style={{ maxWidth: 450 }}>
                  <Image src={FeaturesImage} alt="home_image" className={style.home_image_cotainer} />
                </div>
              </div>
            </div>
            <div className={style.home_features_section_container_02}>
              <div style={{ marginTop: 20 }}>
                <div style={{ maxWidth: 450 }}>
                  <Image src={FeaturesImage} alt="home_image" className={style.home_image_cotainer} />
                </div>
              </div>
              <div style={{ marginTop: 20 }}>
                <h3 className={style.home_features_section_subtitle}>Build your strategy</h3>
                <p className={style.home_features_section_text}>After connect your exchange, you are ready to start building your strategy slecting the "Create Bot" feature and setup your entries and exits conditions based on indicators and custom settings. Subscribers have the option to quick start with "Templates" feature.</p>
              </div>
            </div>
            <div className={style.home_features_section_container_03}>
              <div>
                <h3 className={style.home_features_section_subtitle}>Analyze the results</h3>
                <p className={style.home_features_section_text}>You can easely follow your bot results ont the Strategy dashboard and check in details all oppened and closed orders. Bots can be paused, edited or deleted at any time and all errors such as insufucient balance or credentials issues can be trackked in the "Event Logs" tab.</p>
              </div>
              <div style={{ marginBottom: 20 }}>
                <div style={{ maxWidth: 450 }}>
                  <Image src={FeaturesImage} alt="home_image" className={style.home_image_cotainer} />
                </div>
              </div>
            </div>
            <div className={style.home_price_section} id="pricing">
              <div>
                <h2 className={style.home_price_section_title}>Simple, transarent pricing</h2>
                <p className={style.home_price_section_subtitle}>Start your free tier now and upgrade to our professional trader features as you go. There are no extra fees or commissions per trade.</p>
              </div>
            </div>
            <div className={style.home_flex_center} style={{ borderBottom: 'solid 1px rgba(255,255,255,0.15)', width: '100%', marginBottom: 50 }}>
              <PlanOptions setPlantype={setPlantype} planType={planType} />
            </div>
            <div className={style.home_footer_hero}>
              <h2 className={style.home_footer_hero_title}>Create your trading bots like a professional.</h2>
              <Link href="https://app.tradingrid.com/signup"><a className={style.home_footer_hero_button}>Start Now</a></Link>
            </div>
            <Footer />          
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home