import React from 'react'
import Head from 'next/head'
import Header from '../components/Header.js'
import Footer from '../components/Footer.js'

import style from '../styles/Terms.module.css'

const Terms = () => {

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header id="home">
                <Header />
            </header>
            <main>
                <div className={style.terms_flex_center}>
                    <div className={style.terms_width}>
                        <h1 className={style.terms_title}>Terms of Service</h1>
                        <div className={style.terms_container}>
                            <p className={style.terms_text}>
                                Welcome to Imooby Internet Ltd “Tradingrid” (hereinafter also “Tradingrid” or “we/our”). We
                                offer a software as a service solution “SaaS”, hereinafter referred to as “the Software” through
                                our website tradingrid.com (the “Website”). The Software enables you (the “User”) to create
                                trading bots and automate their operation on third-party cryptocurrency exchanges.
                            </p>
                            <p className={style.terms_text}>
                                These Terms and Conditions (the “Terms”) apply to the relationship between Tradingrid and its
                                Users for any use of the Website and the Software that Tradingrid offers. You are not
                                permitted to use the Website and the Software without accepting these Terms. By accessing
                                the Website, you are agreeing to be bound by these Terms of Service, all applicable laws and
                                regulations, and you agree that you are responsible for compliance with any applicable local
                                laws. If you do not agree with these Terms of Service, you are prohibited from registering,
                                using and subscribing to Tradingrid’s Software. The materials contained on the Website are
                                protected by applicable copyright and trademark law. Please familiarize yourself with our
                                Privacy Policy at tradingrid.com/privacy prior to agreeing to these Terms and Conditions.
                                Please note that using Tradingrid is not: (i) within scope of the jurisdiction of the Financial
                                Ombudsman Service, or (ii) subject to protection under the Financial Services Compensation
                                Scheme, or (iii) within scope of the jurisdiction of, or subject to protection under, either of the
                                schemes referred to in paragraph (i) or (ii)
                            </p>
                        </div>

                        <div className={style.terms_content}>
                            <ol>
                                <li className={style.terms_section_title}>1. Definitions</li>
                                <li className={style.terms_section_text}>1.1 Tradingrid: Tradingrid is a limited liability company incorporated under the laws of the
                                    United Kingdom and Wales. The company is registered under the registration number
                                    11265766. The company’s registered office is at 6, 2 Fisher Close SE16 5AE London, United
                                    Kingdom. </li>
                                <li className={style.terms_section_text}>1.2 User(s): individual consumers or legal entities making use of the Website or Software. Also
                                    referred to as “you”.</li>
                                <li className={style.terms_section_text}>1.3 Software: developed and fully owned by Tradingrid, the Software enables users to create
                                    various trading bots on a user-friendly digital interface.</li>
                                <li className={style.terms_section_text}>1.4 Bots: trading strategies, built with indicators such as but not limited to price, volume and
                                    market capitalization. The range of bots is subject to change in accordance with Tradingrid’s
                                    future amendments to the interface.</li>
                                <li className={style.terms_section_text}>1.5 Free Trial: the trial version of the Software available to users for free for a period of time.
                                    The availability of bots and functionalities of the Software is limited in the Free Trial.</li>
                                <li className={style.terms_section_text}>1.6 Subscription: one of the selected paid plans that permits the User to use the Software. You
                                    can select a monthly or an annual subscription plan upon registration.</li>
                            </ol>
                            <ol>
                                <li className={style.terms_section_title}>2. Registration and personal account</li>
                                <li className={style.terms_section_text}>2.1 If you want to use our Website and Software, go to our Website tradingrid.com</li>
                                <li className={style.terms_section_text}>2.2 To
                                    have initial access to the Software, you will need to register and create a personal account. You
                                    can register using your personal email or opt to log in through your LinkedIn, Google or
                                    Facebook profiles in order to use the Website and the Software</li>
                                <li className={style.terms_section_text}> 2.3 You must protect the login
                                    details of your account and keep your password strictly secret. We will assume that all activity
                                    from your account is carried out by you or under your supervision. </li>
                                <li className={style.terms_section_text}>2.4 You agree to provide
                                    up-to-date, accurate and complete information on your account.</li>
                            </ol>
                            <ol>
                                <li className={style.terms_section_title}>3. Offers and prices</li>
                                <li className={style.terms_section_text}>3.1 All offers and free trials on the Website are without obligations. However, all offers and
                                    free trials are always subject to these Terms.</li>
                                <li className={style.terms_section_text}>3.2 Contingent on your jurisdiction, the prices on the Website can be either inclusive or
                                    exclusive of taxes and expenses.</li>
                                <li className={style.terms_section_text}>3.3 We reserve the right to adjust the prices subject to the digital market conditions. You agree
                                    to any price changes that shall take effect immediately.</li>
                            </ol>
                            <ol>
                                <li className={style.terms_section_title}>4. Free Trial</li>
                                <li className={style.terms_section_text}>4.1 Upon registration, you may have an option to select a Free Trial whereby you would be
                                    entitled to use the Software under a Free Plan for a period of time.</li>
                                <li className={style.terms_section_text}>4.2 Some functionalities are subject to limitations during the Free Trial. Tradingrid reserves the
                                    right to amend the structure, length and availability of trading bot options within the Free
                                    Trial. </li>
                                <li className={style.terms_section_text}>4.3 Tradingrid reserves the right to introduce or withdraw the option for users to select a Free
                                    Trial at any time</li>
                            </ol>
                            <ol>
                                <li className={style.terms_section_title}>5. Subscription and payment</li>
                                <li className={style.terms_section_text}>5.1 You need a Subscription to use the Website and the Software and its range of
                                    functionalities.</li>
                                <li className={style.terms_section_text}>5.2 Subscriptions are offered on the basis of your selected plan for a fixed amount per month
                                    and/or per year. </li>
                                <li className={style.terms_section_text}>5.3 Tradingrid offers several Subscription plans. Each plan differs in terms of but not limited to, access to
                                    trading bots, exchanges, template strategies, learning content and other relevant options.</li>
                                <li className={style.terms_section_text}>5.4 The price of the Subscription will be invoiced automatically every month/year. Possible
                                    methods of payment are authorized via Stripe and are displayed on the Website and include,
                                    for example, credit cards such as Visa or MasterCard. </li>
                                <li className={style.terms_section_text}>5.5 By choosing one of the payment options, you grant your permission for us to initiate a
                                    payment or a series of payments on your behalf via Stripe, which will be marked as a
                                    Merchant-Initiated Transaction (MIT) by Stripe. All your payment details will be confidentially
                                    secured. Neither Tradingrid nor Stripe will have access to your financial data.</li>
                                <li className={style.terms_section_text}>5.6 A monthly subscription will continue for a month-to-month period, unless User cancels the
                                    subscription before the end of the term already paid for.</li>
                                <li className={style.terms_section_text}>5.7 An annual subscription will automatically be extended after expiration, unless User cancels
                                    the subscription before the end of the term already paid for.</li>
                                <li className={style.terms_section_text}>5.8 User can cancel the subscription by the end of the term already paid for. The account of
                                    the User will remain active for the period that User has already paid for.</li>
                                <li className={style.terms_section_text}>5.9 The Data on the User’s account may be subject to deletion after the cancellation of the
                                    Subscription or Trial</li>
                            </ol>
                            <ol>
                                <li className={style.terms_section_title}>6. Cancelation</li>
                                <li className={style.terms_section_text}>Users have the right to cancel their Subscription, Trial and Account at any time</li>
                                <li className={style.terms_section_text}>Tradingrid reserves the right to retain the payments that Users have paid for the amount of time they have selected.</li>
                            </ol>
                            <ol>
                                <li className={style.terms_section_title}>7. Refund Policy</li>
                                <li className={style.terms_section_text}>7.1 If the User paid for a chosen subscription plan and has consequently decided to cancel the
                                    plan following provisions of Clause 6 above, Tradingrid reserves the right to allow the User to
                                    request a refund during the 1 week (7 days) after the end date of the User's Trial Period</li>
                                <li className={style.terms_section_text}>7.2 Following the lapse of one week (7 days) after the end date of the User's Trial Period,
                                    Tradingrid reserves its full discretion to refund requested amounts to subscribers who
                                    cancelled their subscription plans in accordance with Clause 6 above and have not requested a
                                    refund in accordance with Clause 7.1.</li>
                                <li className={style.terms_section_text}>7.3 At all times otherwise, Tradingrid reserves the right to retain the payments that Users have
                                    paid for the amount of time they have selected</li>
                            </ol>
                            <ol>
                                <li className={style.terms_section_title}>8. Account deletion</li>
                                <li className={style.terms_section_text}>If you would like to terminate your activity on Tradingrid and permanently delete your account
                                    and User details, you have a right to request Tradingrid’s Support Team to delete your account
                                    and all the data associated with it. We will not store the data you provided on Tradingrid
                                    during the period of your activity and will delete your account permanently. Please contact us
                                    by email on support@tradingrid.com or via our chat with a request to delete your account.</li>
                            </ol>
                            <ol>
                                <li className={style.terms_section_title}>9. User licence</li>
                                <li className={style.terms_section_text}>9.1 This is the grant of a license, not a transfer of title, meaning you are entitled to temporarily
                                    access the Software during the Free Trial, or alternatively, permanently for the duration of
                                    having a paid Subscription. Under this license you may not: modify or copy the materials; use
                                    the materials for any commercial purpose, or for any public display (commercial or noncommercial); attempt to decompile or reverse engineer any software contained on Tradingrid
                                    's Website; remove any copyright or other proprietary notations from the materials; or
                                    transfer the materials to another person or "mirror" the materials on any other server. Any
                                    intellectual property objects within Tradingrid including all information, data, products,
                                    materials, services, software applications and tools, APIs, design elements, text, images,
                                    photographs, illustrations, audio and video contents, artwork and graphics contained therein
                                    or otherwise made available to you in connection therewith provided through or used to
                                    operate the Software is licensed, not sold, to you by Tradingrid.</li>
                                <li className={style.terms_section_text}>9.2 This license shall be automatically terminated if you violate any of these restrictions and
                                    may be terminated by Tradingrid at any time.</li>
                                <li className={style.terms_section_text}>9.3 For all content and data, that you create or make available via the Software ("User
                                    Tradingrid "), you grant Tradingrid free of charge a transferable, sublicensable, non-exclusive,
                                    irrevocable, worldwide right of use and exploitation and for the maximum term permitted
                                    under applicable law and which is unlimited in terms of content, to use this User Content for
                                    any purpose including but not limited to amend, edit and translate, as well as to store,
                                    reproduce, disseminate, make accessible to the public, send, disclose publicly and non publicly
                                    and otherwise make available the User Content, including, without limitation, all trading
                                    strategies that you create, the names of such trading strategies and any settings that you
                                    create for such trading strategies</li>
                            </ol>
                            <ol>
                                <li className={style.terms_section_title}>10. Limitation of Liability</li>
                                <li className={style.terms_section_text}>10.1 In no event shall Tradingrid or its suppliers be liable for, including but not limited to, any
                                    damages for loss of data, financial losses, business interruption and injury arising out of the
                                    use of or the omission to use any materials on the Website, even if Tradingrid or a Tradingrid
                                    authorized representative has been notified orally or in writing of the possibility of such
                                    damage.</li>
                                <li className={style.terms_section_text}>10.2 To the fullest extent permitted by applicable law, Tradingrid and parties collaborating
                                    with Tradingrid will not be liable to you under any type of liability, whether based in contract,
                                    tort, negligence, strict liability, warranty or otherwise - for any indirect, consequential,
                                    exemplary, incidental, punitive or special damages or profit losses. </li>
                                <li className={style.terms_section_text}>10.3 Clause 10 is universally applicable to all Users, regardless of geographical position or
                                    jurisdiction.</li>
                            </ol>
                            <ol>
                                <li className={style.terms_section_title}>11. Links</li>
                                <li className={style.terms_section_text}>11.1 Tradingrid reserves the right to not fully review all of the sites linked to its Website and is not
                                    responsible for the contents of any linked site. The legitimacy and reliability of the data
                                    provided by the Websites referred to on Tradingrid’s Website is limited to the obligations to
                                    those Websites’ operators.
                                </li>
                            </ol>
                            <ol>
                                <li className={style.terms_section_title}>12. Modifications</li>
                                <li className={style.terms_section_text}>12.1 Tradingrid may revise these Terms or its Website at any time without notice. By using this
                                    Website, you are agreeing to be bound by the then current version of these terms of service</li>
                            </ol>
                            <ol>
                                <li className={style.terms_section_title}>13. Trademarks</li>
                                <li className={style.terms_section_text}>13.1 Tradingrid.com and our logos, product service names, slogans and the Software are
                                    trademarks of Tradingrid and may not be copied, imitated or used, in whole or in part, without
                                    our prior written authorization. All other trademarks, registered trademarks, product names
                                    and company names or logos mentioned on the Services are the property of their respective
                                    owners. Reference to any products, services, processes or other information by trade name,
                                    trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement,
                                    sponsorship or recommendation by us</li>
                            </ol>
                            <ol>
                                <li className={style.terms_section_title}>General</li>
                                <li className={style.terms_section_text} style={{ marginBottom: 15 }}>ALL INFORMATION CONTAINED ON THE WEBSITE AND ITS SERVICES IS FOR GENERAL
                                    INFORMATIONAL USE ONLY AND SHOULD NOT BE RELIED UPON BY YOU IN MAKING ANY
                                    INVESTMENT DECISION. THE WEBSITE AND SERVICES DO NOT PROVIDE INVESTMENT ADVICE
                                    AND NOTHING ON THE WEBSITE AND SERVICES SHOULD BE CONSTRUED AS BEING
                                    INVESTMENT ADVICE. BEFORE MAKING ANY INVESTMENT CHOICE, YOU SHOULD ALWAYS
                                    CONSULT A FULLY QUALIFIED FINANCIAL AND/OR INVESTMENT ADVISER. </li>
                                <li className={style.terms_section_text} style={{ marginBottom: 15 }}>The Website and the Software include and/or may include advertisements and links to
                                    external sites and co-branded pages or promote Websites or services from other companies or
                                    offer you the ability to download software or content from other companies in order to
                                    provide you with access to information and services which you may find useful or interesting.
                                    Tradingrid does not endorse such sites nor approve any content, information, legal or illegal
                                    emails (whether spam emails or not), goods or services provided by them. Tradingrid is not
                                    responsible for and does not control those Websites, services, emails, content and software
                                    and cannot accept any responsibility or liability for any loss or damage suffered by you as a
                                    result of your use of its Website and services or of such external and/or co-branded sites.</li>
                                <li className={style.terms_section_text}>Tradingrid is unable to exercise control over the security or content of information passing
                                    over the network, and Tradingrid hereby excludes all liability of any kind for the transmission
                                    or reception of infringing or unlawful information of whatever nature.</li>
                            </ol>
                            <ol>
                                <li className={style.terms_section_text} style={{ marginTop: 15, fontWeight: 400 }}>Imooby Internet Ltd "Tradingrid"</li>
                                <li className={style.terms_section_text}>Address: street Francisco Rocha, 198 Curitiba-PR | Brazil</li>
                                <li className={style.terms_section_text}>Contact: support@tradingrid.com</li>
                                <li className={style.terms_section_text}>Website: https://tradingrid.com</li>
                            </ol>
                        </div>
                        <Footer />

                    </div>
                </div>
            </main>

        </div>
    )
}

export default Terms
